// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm-OmFjl5A55MtbJGZefPZNjbaKiacueo',
    appId: '1:624646487323:web:87b5e6617f7a4dad6aa7be',
    messagingSenderId: '624646487323',
    projectId: 'seequarium',
    authDomain: 'seequarium.firebaseapp.com',
    storageBucket: 'seequarium.appspot.com',
    measurementId: 'G-JD79V96S4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF78jnlvxo3-Fea6oufI-LWHEFT82a-fQ',
    appId: '1:624646487323:android:a2e146715f3d36626aa7be',
    messagingSenderId: '624646487323',
    projectId: 'seequarium',
    storageBucket: 'seequarium.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnyJNMt_XJ1evJ5xoFvLU9zy6Xs0hVRoU',
    appId: '1:624646487323:ios:6a269146d76b4ff26aa7be',
    messagingSenderId: '624646487323',
    projectId: 'seequarium',
    storageBucket: 'seequarium.appspot.com',
    iosBundleId: 'com.example.seequarium',
  );
}
